apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: minio
  labels: { app: minio }
spec:
  clusterIP: None
  selector: { app: minio }
  ports:
  - { name: api , port: 9000 }
  - { name: console , port: 9443 }
